#
# Automatically approves pull requests opened by keyman-server
# The initial use of this action is to upload product help documentation
# with resources/build/help-keyman-com.sh.
# That script creates a PR and then this workflow will be
# triggered to approve the PR, and then auto-merge-keyman-server-pr.yml
# will merge it
#
name: Auto Approve PRs from keyman-server

on: pull_request_target

jobs:
  deets:
    runs-on: ubuntu-latest
    steps:
    - run: |
           echo "actor: ${{github.actor}}"
           echo "head: ${{github.event.pull_request.head.ref}}"
           echo "head_ref: ${{github.head_ref}}"
           echo "hsw: .${{startsWith(github.head_ref, 'auto/')}}."

  auto-approve:
    if: github.actor == 'mcdurdin' && startsWith(github.event.pull_request.head.ref, 'auto/')
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    permissions:
      pull-requests: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1
      with:
        sparse-checkout: |
          README.md
        sparse-checkout-cone-mode: false
    - name: Approve pull request
      run: |
           gh pr review --approve ${{github.head_ref}}
    - name: Enable auto-merge
      run: |
           gh pr merge --merge --auto ${{github.head_ref}}
